version: "2"

linters:
  default: all

  disable:
    - depguard
    - exhaustruct

  settings:
    revive:
      enable-all-rules: true

      rules:
        - name: line-length-limit
          severity: warning
          disabled: true
        - name: package-comments
          severity: warning
          disabled: true

formatters:
  enable:
    - gofmt
run:
  timeout: 5m
  tests: false
  allow-parallel-runners: true
  allow-serial-runners: true
  go: '1.24'