version: "2"

linters:
  default: all

  # Disable specific linters.
  disable:
    - depguard
    - exhaustruct

  settings:
    revive:
      # Enable all available rules.
      # Default: false
      enable-all-rules: true

      rules:
        - name: line-length-limit
          severity: warning
          disabled: true
        - name: package-comments
          severity: warning
          disabled: true

  exclusions:
    paths:
      - ".*\\.mock\\.go$"
      - "^mock/.*"

formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - ".*\\.mock\\.go$"
      - "^mock/.*"
run:
  timeout: 5m
  tests: false
  allow-parallel-runners: true
  allow-serial-runners: true
  go: '1.24'