env: "local"

external_service_timeout: "30s"
executor_num_goroutines: 100

postgres:
  host: "localhost"
  port: 5432
  name: "task_executor"
  sslmode: "disable"
  driver: "pgx"
  user: "task_executor_user"
  password: "1234"

logger:
  filename: "./logs/task_executor.log"
  format: "json"
  level: "info"

kafka:
  addresses:
    - "localhost:9091"
  topic: "task-topic"
  consumer_group: "task-consumer-group"