env: "prod"

http_server:
  host: localhost
  port: 8081
  read_timeout: "5s"
  write_timeout: "5s"

external_service_timeout : "30s"

postgres:
  host: "localhost"
  port: 5432
  name: "task_executor"
  sslmode: "disable"
  driver: "pgx"
  user: "task_executor_user"
  password: "1234"

logger:
  filename: "./logs/task_executor_http.log"
  format: "json"
  level: "info"

kafka:
  addresses:
    - "localhost:9091"
  topic: "task-topic"